name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Обновляется каждый день в 00:00 UTC
  workflow_dispatch:     # Можно запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          username: miragiee
          theme: one-dark
          days: 31
          height: 300
          hide_border: true
