name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: miragiee
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#0e4429,#006d32,#26a641,#39d353,#26a641
