name: Generate Snake For Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: miragiee
          outputs: |
            github-snake.svg
            github-snake-onedark.svg?color_snake=#e06c75&color_dots=#282c34,#3e4451,#5c6370,#61afef,#c678dd
