name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Обновление каждый день в полночь
  workflow_dispatch:  # Ручной запуск

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: miragiee
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: main
          keep_files: true
